// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrsxsyvowodxhrpiwjej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyc3hzeXZvd29keGhycGl3amVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzA1NDYsImV4cCI6MjA2MDM0NjU0Nn0.QGPBP5SuuUXjoSDEyAWSkTHVjauRZrIoAOLI2YCaFqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);